name: Rotate Daily Song

on:
    workflow_dispatch:  # This allows you to manually trigger the workflow
    schedule:
        - cron: '0 5 * * *'  # This schedules the workflow to run at 12am EST (which is 5am UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        GENIUS_CLIENT_ACCESS_TOKEN: ${{ secrets.GENIUS_CLIENT_ACCESS_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Run script
      run: python api/token_in_url.py

    - name: Upload to CloudFlare R2 Bucket
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        r2-bucket: ${{ secrets.R2_BUCKET }}
        source-dir: lyrics/
        destination-dir: ./
